In [4]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model


In [5]:
matches_for_predict = pd.read_csv('matches_for_predict.csv')
futureM = pd.read_csv('Futures.csv')
model = load_model("FinalData.h5")


In [6]:
predictions = model.predict(matches_for_predict)
for index, predict in enumerate(predictions):
    print(f'{futureM.loc[index, "Team"]} VS {futureM.loc[index, "Opponent"]}')
    print(predict)
    if np.argmax(predict) == 1:
        print("***** Draw *****")
    elif np.argmax(predict) == 0:
        if futureM.loc[index, "Venue"] == 'Home':
            print(
                f"Home team wins. ***** {futureM.loc[index, 'Team']} *****")
        elif futureM.loc[index, "Venue"] == 'Away':
            print(
                f"Away team wins. ***** {futureM.loc[index, 'Team']} *****")
    else:
        if futureM.loc[index, "Venue"] == 'Home':
            print(
                f"Away team wins. ***** {futureM.loc[index, 'Opponent']} *****")
        elif futureM.loc[index, "Venue"] == 'Away':
            print(
                f"Away team wins. ***** {futureM.loc[index, 'Team']} *****")
    # print(predict)
    print('---------------------------------------------------------')
    print('---------------------------------------------------------')


2/2 [==============================] - 0s 7ms/step
3 VS 258
[0.9494486  0.02438287 0.02616853]
---------------------------------------------------------
---------------------------------------------------------
5 VS 334
[0.89965934 0.06479283 0.03554785]
---------------------------------------------------------
---------------------------------------------------------
156 VS 20
[0.9503293  0.02356083 0.0261098 ]
---------------------------------------------------------
---------------------------------------------------------
1 VS 1
[0.92763644 0.0346843  0.03767929]
---------------------------------------------------------
---------------------------------------------------------
12 VS 11
[0.9395821  0.02898508 0.03143281]
---------------------------------------------------------
---------------------------------------------------------
9 VS 8
[0.03863236 0.03582756 0.92554015]
---------------------------------------------------------
--------------------------------------------------

In [ ]:
predictions = model.predict(matches_for_predict)
for index, predict in enumerate(predictions):
    print(f'{futureM.loc[index, "Team"]} VS {futureM.loc[index, "Opponent"]}')
    if np.argmax(predict) == 1:
        print("***** Draw *****")
    elif np.argmax(predict) == 0:
        if futureM['Venue'].iloc[index] == 'Home':
            print(
                f"Home team wins. ***** {futureM['Team'].iloc[index]} *****")
        elif futureM['Venue'].iloc[index] == 'Away':
            print(
                f"Away team wins. ***** {futureM['Team'].iloc[index]} *****")
    else:
        if futureM['Venue'].iloc[index] == 'Home':
            print(
                f"Away team wins. ***** {futureM['Opponent'].iloc[index]} *****")
        elif futureM['Venue'].iloc[index] == 'Away':
            print(
                f"Away team wins. ***** {futureM['Team'].iloc[index]} *****")
    # print(predict)
    print('---------------------------------------------------------')
    print('---------------------------------------------------------')


2/2 [==============================] - 0s 0s/step
Liverpool VS Manchester City
Home team wins. ***** Liverpool *****
---------------------------------------------------------
---------------------------------------------------------
Arsenal VS Brentford
Home team wins. ***** Arsenal *****
---------------------------------------------------------
---------------------------------------------------------
Aston Villa VS Tottenham
Home team wins. ***** Aston Villa *****
---------------------------------------------------------
---------------------------------------------------------
Manchester Utd VS Everton
Home team wins. ***** Manchester Utd *****
---------------------------------------------------------
---------------------------------------------------------
West Ham VS Burnley
Home team wins. ***** West Ham *****
---------------------------------------------------------
---------------------------------------------------------
Newcastle Utd VS Chelsea
Away team wins. ***** Newcastl