In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model


In [2]:
matches_for_predict = pd.read_csv('matches_for_predict.csv')
futureM = pd.read_csv('Futures.csv')
model = load_model("FinalData.h5")


In [5]:
predictions = model.predict(matches_for_predict)
for index, predict in enumerate(predictions):
    print(f'{futureM.loc[index, "Team"]} VS {futureM.loc[index, "Opponent"]}')
    print(predict)
    if np.argmax(predict) == 1:
        print("***** Draw *****")
    elif np.argmax(predict) == 0:
        if futureM.loc[index, "Venue"] == 'Home':
            print(
                f"Home team wins. ***** {futureM.loc[index, 'Team']} *****")
        elif futureM.loc[index, "Venue"] == 'Away':
            print(
                f"Away team wins. ***** {futureM.loc[index, 'Team']} *****")
    else:
        if futureM.loc[index, "Venue"] == 'Home':
            print(
                f"Away team wins. ***** {futureM.loc[index, 'Opponent']} *****")
        elif futureM.loc[index, "Venue"] == 'Away':
            print(
                f"Away team wins. ***** {futureM.loc[index, 'Team']} *****")
    # print(predict)
    print('---------------------------------------------------------')
    print('---------------------------------------------------------')


2/2 [==============================] - 0s 6ms/step
Liverpool VS Manchester City
[0.8643943  0.11665422 0.01895143]
Home team wins. ***** Liverpool *****
---------------------------------------------------------
---------------------------------------------------------
Arsenal VS Brentford
[0.94368094 0.04986361 0.00645546]
Home team wins. ***** Arsenal *****
---------------------------------------------------------
---------------------------------------------------------
Aston Villa VS Tottenham
[0.9686465  0.02860451 0.00274895]
Home team wins. ***** Aston Villa *****
---------------------------------------------------------
---------------------------------------------------------
Manchester Utd VS Everton
[0.8669074  0.10252599 0.03056666]
Home team wins. ***** Manchester Utd *****
---------------------------------------------------------
---------------------------------------------------------
West Ham VS Burnley
[0.94443333 0.04772392 0.00784267]
Home team wins. ***** West Ham *

In [ ]:
predictions = model.predict(matches_for_predict)
for index, predict in enumerate(predictions):
    print(f'{futureM.loc[index, "Team"]} VS {futureM.loc[index, "Opponent"]}')
    if np.argmax(predict) == 1:
        print("***** Draw *****")
    elif np.argmax(predict) == 0:
        if futureM['Venue'].iloc[index] == 'Home':
            print(
                f"Home team wins. ***** {futureM['Team'].iloc[index]} *****")
        elif futureM['Venue'].iloc[index] == 'Away':
            print(
                f"Away team wins. ***** {futureM['Team'].iloc[index]} *****")
    else:
        if futureM['Venue'].iloc[index] == 'Home':
            print(
                f"Away team wins. ***** {futureM['Opponent'].iloc[index]} *****")
        elif futureM['Venue'].iloc[index] == 'Away':
            print(
                f"Away team wins. ***** {futureM['Team'].iloc[index]} *****")
    # print(predict)
    print('---------------------------------------------------------')
    print('---------------------------------------------------------')


2/2 [==============================] - 0s 0s/step
Liverpool VS Manchester City
Home team wins. ***** Liverpool *****
---------------------------------------------------------
---------------------------------------------------------
Arsenal VS Brentford
Home team wins. ***** Arsenal *****
---------------------------------------------------------
---------------------------------------------------------
Aston Villa VS Tottenham
Home team wins. ***** Aston Villa *****
---------------------------------------------------------
---------------------------------------------------------
Manchester Utd VS Everton
Home team wins. ***** Manchester Utd *****
---------------------------------------------------------
---------------------------------------------------------
West Ham VS Burnley
Home team wins. ***** West Ham *****
---------------------------------------------------------
---------------------------------------------------------
Newcastle Utd VS Chelsea
Away team wins. ***** Newcastl