In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model

In [2]:
matches_for_predict = pd.read_csv('matches_for_predict.csv')
futureM = pd.read_csv('Futures.csv')
model = load_model("FinalData.h5")

In [3]:
predictions = model.predict(matches_for_predict)
for index, predict in enumerate(predictions):
    print(f'{futureM.loc[index, "Team"]} VS {futureM.loc[index, "Opponent"]}')
    if np.argmax(predict) == 1:
        print(f"***** {futureM['Team'].iloc[index]} wins *****")
    elif np.argmax(predict) == 0:
        print("***** Draw *****")
    else:
        print(f"***** {futureM['Opponent'].iloc[index]} wins *****")
    print(predict)
    print('--------------------------------')

2/2 [==============================] - 0s 6ms/step
Liverpool VS Manchester City
***** Manchester City wins *****
[0.01142147 0.1606614  0.82791716]
--------------------------------
Arsenal VS Brentford
***** Draw *****
[0.44014347 0.16717097 0.39268562]
--------------------------------
Aston Villa VS Tottenham
***** Draw *****
[0.45293158 0.20973794 0.33733055]
--------------------------------
Manchester Utd VS Everton
***** Everton wins *****
[0.00874617 0.04676555 0.9444883 ]
--------------------------------
West Ham VS Burnley
***** Burnley wins *****
[0.01587334 0.37492463 0.6092021 ]
--------------------------------
Newcastle Utd VS Chelsea
***** Chelsea wins *****
[0.02416093 0.06002698 0.9158121 ]
--------------------------------
Brighton VS Nott'ham Forest
***** Nott'ham Forest wins *****
[0.07881515 0.07698687 0.844198  ]
--------------------------------
Wolves VS Fulham
***** Fulham wins *****
[0.0384494  0.16944009 0.7921105 ]
--------------------------------
Bournemouth VS 